# Theme Settings
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "zh-CN"
title                    : "Youbin Chen"
title_separator          : "-"
name                     : "Youbin Chen"
description              : "谈论数学、物理、科幻、人生及其他的博客"
url                      : "https://chenyoubin1023.github.io"
words_per_minute         : 20
#comments:
  #provider               : "disqus"
  #disqus:
    #shortname            : "tianyikillua"
search                   : true
search_full_content      : true
#search_provider          : algolia
#algolia:
  #application_id         : 5ODSKX9P06
  #index_name             : Blog
  #search_only_api_key    : 01c79c59b07558a5bba71b1347ead4d9
  #powered_by             : true

# Social Sharing
social:
  links:
    - "https://www.linkedin.com/in/youbin-chen/"

# Analytics
#analytics:
  #provider               : "google-universal"
  #google:
    #tracking_id          : "UA-16692644-8"

# Site Author
author:
  name             : "Youbin Chen"
  avatar           : "/assets/images/avatar.png"
  bio              : "固体力学博士"
  location         : "Paris"
  links:
    #- label: "CV"
      #icon: "fas fa-fw fa-user-circle"
      #url: "https://github.com/tianyikillua/cv/blob/master/cv.pdf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chenyoubin1023"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/youbin-chen"
    #- label: "Bitbucket"
      #icon: "fab fa-fw fa-bitbucket"
      #url: "http://bitbucket.org/litianyi"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chenyoubin1023"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/youbin-chen"
    #- label: "Bitbucket"
      #icon: "fab fa-fw fa-bitbucket"
      #url: "http://bitbucket.org/litianyi"

# Reading Files
include:
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      classes: wide
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
      comments: true
      share: true
